name: CI

on:
  pull_request: {}
  push: { branches: [main] }

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build:
    name: Build for ${{ matrix.targetPlatform }} on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        unityVersion:
          - 2019.4.18f1
        targetPlatform:
          - StandaloneWindows64
          - WebGL
          - Android
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v1.1.0
        with:
          path: Library
          key: Library

      # Build
      - name: Build project non WebGL
        uses: game-ci/unity-builder@v2.0-alpha-6
        if: matrix.targetPlatform != 'WebGL'
        with:
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
          
      # Build WebGL
      - name: Build project WebGL
        uses: game-ci/unity-builder@v2.0-alpha-6
        if: matrix.targetPlatform == 'WebGL'
        with:
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
          customImage: 'jcheatley/unity-web-gl:latest'

      # Output
      - uses: actions/upload-artifact@v1
        with:
          name: Build
          path: build
